package lms.view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUser = new javax.swing.JButton();
        newBook = new javax.swing.JButton();
        bookLog = new javax.swing.JButton();
        issueBook = new javax.swing.JButton();
        returnBook = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        newUser.setText("New User");
        newUser.setPreferredSize(new java.awt.Dimension(160, 60));
        newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserActionPerformed(evt);
            }
        });
        getContentPane().add(newUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 15, -1, -1));

        newBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        newBook.setText("New Book");
        newBook.setPreferredSize(new java.awt.Dimension(160, 60));
        newBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookActionPerformed(evt);
            }
        });
        getContentPane().add(newBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        bookLog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bookLog.setText("Book Log");
        bookLog.setPreferredSize(new java.awt.Dimension(160, 60));
        bookLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookLogActionPerformed(evt);
            }
        });
        getContentPane().add(bookLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        issueBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        issueBook.setText("Issue Book");
        issueBook.setPreferredSize(new java.awt.Dimension(160, 60));
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });
        getContentPane().add(issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        returnBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBook.setText("Return Book");
        returnBook.setPreferredSize(new java.awt.Dimension(160, 60));
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setText("Log out");
        logout.setPreferredSize(new java.awt.Dimension(160, 60));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed
// above is for logout button
    private void newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewUser().setVisible(true);
    }//GEN-LAST:event_newUserActionPerformed
// above is for new student button
    private void newBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBookActionPerformed
// above is for new book button
    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issueBookActionPerformed
//above is for issue book button
    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_returnBookActionPerformed
//above is for return book button
    private void bookLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookLogActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BookLog().setVisible(true);
    }//GEN-LAST:event_bookLogActionPerformed
//above is for statistics button
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookLog;
    private javax.swing.JButton issueBook;
    private javax.swing.JButton logout;
    private javax.swing.JButton newBook;
    private javax.swing.JButton newUser;
    private javax.swing.JButton returnBook;
    // End of variables declaration//GEN-END:variables
}
