/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms.view;

/**
 *
 * @author User
 */
public class StudentHome extends javax.swing.JFrame {
    private String studentId;
    private String userType = "student";
    /**
     * Creates new form studentHome
     */
    public StudentHome(String studentId) {
        initComponents();
        this.studentId = studentId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseLibrary = new javax.swing.JButton();
        viewCurrentlyCheckedOut = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        browseLibrary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        browseLibrary.setText("Browse Library");
        browseLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseLibraryActionPerformed(evt);
            }
        });

        viewCurrentlyCheckedOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewCurrentlyCheckedOut.setText("View Current Checkouts");
        viewCurrentlyCheckedOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentlyCheckedOutActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCurrentlyCheckedOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browseLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(browseLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewCurrentlyCheckedOut, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(logout)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void viewCurrentlyCheckedOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentlyCheckedOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewCurrentlyCheckedOut(this.studentId).setVisible(true);        
    }//GEN-LAST:event_viewCurrentlyCheckedOutActionPerformed

    private void browseLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseLibraryActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BrowseLibrary(this.studentId,this.userType).setVisible(true);
    }//GEN-LAST:event_browseLibraryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseLibrary;
    private javax.swing.JButton logout;
    private javax.swing.JButton viewCurrentlyCheckedOut;
    // End of variables declaration//GEN-END:variables
}
